import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import NPProgresProvider from "@/components/provider/np-progress-provider";
import ThemeProvider from "@/components/provider/theme-provider";
import ReactQueryProvider from "@/components/provider/react-query-provider";
import NextAuthProvider from "@/components/provider/next-auth-provider";
import { Toaster } from "@/components/ui/toaster";

const nunito = Nunito({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    template: "%s | Note App",
    default: "Note App",
  },
  description: "Official Note App by Arief Rachman Hakim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={nunito.className} suppressHydrationWarning>
        <NPProgresProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <ReactQueryProvider>
              <NextAuthProvider>{children}</NextAuthProvider>
            </ReactQueryProvider>
          </ThemeProvider>
        </NPProgresProvider>
        <Toaster />
      </body>
    </html>
  );
}
